### PR TITLE
use strerror_r

### PR DESCRIPTION
**Pull request by aleks-f**
`strerror()` is not thread-safe, replace with `strerror_r()` and add MSVC shim

### CODE REVIEW

**Comment by skeeto** [comment]
I'm kind of torn over this. strerror() is a standard C function, and it 
always has been. While technically it's not necessarily thread-safe, 
it's utterly trivial to implement in a thread-safe manner anyway, which 
is how glibc, musl, and diet all do it (all Linux). The int argument is 
just an index into a static string table, as it should be. However, it 
appears both MSVCRT and BSD's libc do the idiotic thing of copying the 
error message to a static buffer. That's why MSVC warns about it.

As in your PR, the fix is to use strerror_r(), but this function comes 
from POSIX (POSIX.1-2001). It's not standard C, which is why MSVC 
doesn't provide it, instead supplying its own non-standard version, 
strerror_s(). There's no way to get the error message description in a 
thread-safe way in standard C — which honestly makes it all the more 
important that implementations don't do the stupid thing.

Third annoyance: GNU invented their own strerror_r(), which I assume 
predates the POSIX version, and it has a slightly different prototype. 
Fortunately it only differs by return type, but it does complicate 
things a little more.

Accepting this change means the library behaves better under 
multi-threaded MSVC and BSD environments, but it's no longer a pure C 
library, which is something I strive for. Compiling under a host that is 
neither POSIX nor MSVC requires changes.

Finally, to be 100% technically correct for POSIX platforms, it needs 
this line in json.c before including any headers (I can do this in a 
follow-up commit if you don't know what I mean):

    #define _POSIX_C_SOURCE 201112L

Since the Makefile specifies -std=c99, this is required, at least on 
Linux (feature test macros), in order to build correctly.

**Comment by aleks-f** [comment]
I understand, the rationale and technicalities.

So, if I add the said define, will you accept the contribution? Would an #ifdef for preservation of C99 purity make it more palatable?

**Comment by skeeto** [comment]
I was mostly just talking it out. The pragmatic thing to do is accept 
this, so I just did. Are you actually using this in a multi-threaded 
environment, or were you more concerned about warnings?

**Comment by aleks-f** [comment]
@skeeto we use it in [POCO::JSON](https://github.com/pocoproject/poco/tree/develop/JSON), so it may end up in all kinds of scenarios on many platforms; MSVC warnings are just an additional annoyance. Thanks for accepting it.

**Pull request merged**
